name: raylib_dart
description: FFI bindings for raylib, a simple and easy-to-use library for creating games and multimedia applications with Dart.
version: 0.0.7
repository: https://github.com/dzylikecode/raylib
homepage: https://github.com/dzylikecode/raylib

environment:
  sdk: ^3.10.0

dependencies:
  logging: ^1.3.0
  hooks: ^1.0.0
  native_toolchain_cmake: ^0.2.0
  code_assets: ^1.0.0
  ffi: ^2.1.4
  meta: ^1.17.0
  vector_math: ^2.2.0

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.0.0
  test: ^1.25.6
