name: raylib
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  logging: ^1.3.0
  hooks: ^1.0.0
  native_toolchain_cmake: ^0.2.0
  code_assets: ^1.0.0
  ffi: ^2.1.4
  # path: ^1.9.0

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.0.0
  test: ^1.25.6
